---

  - name: Create/update test db
    hosts: "{{ hosts|default('local') }}"
    tasks:
      - name: install postgres
        tags:
          - install
        apt: name=postgresql update_cache=yes
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: install psycopg2
        tags:
          - install
        pip: name=psycopg2

      - name: create_user
        become: yes
        become_user: postgres
        tags:
          - pg
        postgresql_user: name=testdb password=testdb role_attr_flags=CREATEDB,NOSUPERUSER

      - name: create_db
        become: yes
        become_user: postgres
        tags:
          - pg
        postgresql_db: name=testdb owner=testdb
